import Head from 'next/head';
import NavBar from '../components/Navbar';
import About from '../components/About';
import Services from '../components/Services';
import Landing from '../components/Landing';
import Contact from '../components/Contact';
import Footer from '../components/Footer';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Santa Cruz</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="https://genfavicon.com/tmp/icon_399005da7bc685e99ce114abf893a9d2.ico" />
			</Head>

			<NavBar />
			<Landing />
			<About />
			<Services />
			<hr class="my-8 border-white sm:mx-auto lg:my-8" />
			<Contact />
			<Footer />
		</div>
	);
}
